name: gym
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  get_it: ^7.6.7
  google_nav_bar: ^5.0.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  fluttertoast: ^8.2.4
  flutter_launcher_icons: ^0.13.1
  animate_do: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter_icons:
  android: true
  image_path: "assets/images/gym.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/




  # flutter pub run flutter_launcher_icons:main
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
